language: node_js
before_script:
  - psql -c 'create database connect_pg_simple_test;' -U postgres
sudo: false
script: npm test
after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
matrix:
  include:
    - node_js: "8"
      addons:
        postgresql: "9.5"
    - node_js: "8"
      addons:
        postgresql: "9.6"
    - node_js: "9"
      addons:
        postgresql: "9.6"
    - node_js: "10"
      addons:
        postgresql: "9.6"
    - node_js: "node"  # latest stable
      addons:
        postgresql: "9.6"
